// Films
const films = [
	"The Godfather",
	"Pulp Fiction",
	"Inception",
	"The Dark Knight",
	"Titanic",
	"Forrest Gump",
	"Star Wars: A New Hope",
	"The Matrix",
	"The Lion King",
	"The Shawshank Redemption",
	"Jurassic Park",
	"The Lord of the Rings: The Fellowship of the Ring",
	"Gladiator",
	"Schindler's List",
	"The Silence of the Lambs",
	"Back to the Future",
	"Avengers: Endgame",
	"Goodfellas",
	"Fight Club",
	"Interstellar",
	"Braveheart",
	"The Departed",
	"Casablanca",
	"Saving Private Ryan",
	"The Prestige",
	"The Social Network",
	"Mad Max: Fury Road",
	"Spider-Man: Into the Spider-Verse",
	"The Truman Show",
	"Joker",
	"Django Unchained",
	"Parasite",
	"12 Angry Men",
	"The Green Mile",
	"Memento",
	"Black Panther",
	"Deadpool",
	"The Avengers",
	"The Hunger Games",
	"Doctor Strange",
	"Iron Man",
	"The Revenant",
	"La La Land",
	"Whiplash",
	"The Wolf of Wall Street",
	"Get Out",
	"The Irishman",
	"Logan",
	"The Hateful Eight",
	"The Grand Budapest Hotel",
	"Shutter Island",
	"The Sixth Sense",
	"Her",
	"A Beautiful Mind",
	"Guardians of the Galaxy",
	"Thor: Ragnarok",
	"Blade Runner 2049",
	"The Big Lebowski",
	"The Incredibles",
	"Coco",
	"Ratatouille",
	"Frozen",
	"Toy Story",
	"The Lego Movie",
	"Monsters, Inc.",
	"Finding Nemo",
	"Shrek",
	"Kung Fu Panda",
	"Up",
	"Inside Out",
	"Zootopia",
	"The Jungle Book",
	"The Little Mermaid",
	"Beauty and the Beast",
	"Aladdin",
	"Moana",
	"Mulan",
	"Lilo & Stitch",
	"The Princess and the Frog",
	"Tarzan",
	"Frozen II",
	"Toy Story 3",
	"Toy Story 4",
	"How to Train Your Dragon",
	"Despicable Me",
	"Minions",
	"The Secret Life of Pets",
	"Ice Age",
	"Madagascar",
	"Megamind",
	"Trolls",
	"Hotel Transylvania",
	"Cloudy with a Chance of Meatballs",
	"The Lorax",
	"Cars",
	"Cars 2",
	"Cars 3",
	"Planes",
	"WALL-E",
	"A Bug's Life",
	"Ant-Man",
	"Thor",
	"Captain America: The First Avenger",
	"Captain Marvel",
	"Avengers: Infinity War",
	"The Amazing Spider-Man",
	"X-Men",
	"X-Men: Days of Future Past",
	"X-Men: Apocalypse",
	"X-Men: First Class",
	"X2",
	"Fantastic Four",
	"Fantastic Beasts and Where to Find Them",
	"Harry Potter and the Sorcerer's Stone",
	"Harry Potter and the Chamber of Secrets",
	"Harry Potter and the Prisoner of Azkaban",
	"Harry Potter and the Goblet of Fire",
	"Harry Potter and the Order of the Phoenix",
	"Harry Potter and the Half-Blood Prince",
	"Harry Potter and the Deathly Hallows: Part 1",
	"Harry Potter and the Deathly Hallows: Part 2",
	"Twilight",
	"The Twilight Saga: New Moon",
	"The Twilight Saga: Eclipse",
	"The Twilight Saga: Breaking Dawn – Part 1",
	"The Twilight Saga: Breaking Dawn – Part 2",
	"Percy Jackson & the Olympians: The Lightning Thief",
	"Percy Jackson: Sea of Monsters",
	"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
	"The Chronicles of Narnia: Prince Caspian",
	"The Chronicles of Narnia: The Voyage of the Dawn Treader",
	"The Maze Runner",
	"Maze Runner: The Scorch Trials",
	"Maze Runner: The Death Cure",
	"Divergent",
	"Insurgent",
	"Allegiant",
	"The Fault in Our Stars",
	"Me Before You",
	"The Perks of Being a Wallflower",
	"Love, Simon",
	"To All the Boys I've Loved Before",
	"The Kissing Booth",
	"The Sisterhood of the Traveling Pants",
	"The Princess Diaries",
	"The Devil Wears Prada",
	"Pitch Perfect",
	"Legally Blonde",
	"Mean Girls",
	"10 Things I Hate About You",
	"Clueless",
	"She's All That",
	"A Walk to Remember",
	"The Notebook",
	"Dear John",
	"Safe Haven",
	"The Vow",
	"50 First Dates",
	"Crazy, Stupid, Love",
	"La La Land",
	"The Holiday",
	"Love Actually",
	"Bridget Jones's Diary",
	"Notting Hill",
	"Four Weddings and a Funeral",
	"The Wedding Planner",
	"My Best Friend's Wedding",
	"27 Dresses",
	"Runaway Bride",
	"Pretty Woman",
	"The Proposal",
	"The Ugly Truth",
	"What Happens in Vegas",
	"The Bounty Hunter",
	"Just Go with It",
	"Blended",
	"Fifty Shades of Grey",
	"Fifty Shades Darker",
	"Fifty Shades Freed",
	"The Age of Adaline",
	"The Longest Ride",
	"The Lucky One",
	"Safe Haven",
	"The Best of Me",
	"The Choice",
	"The Last Song",
	"Dear John",
	"A Walk to Remember",
	"The Notebook",
	"Love & Other Drugs",
	"One Day",
	"If I Stay",
	"The Spectacular Now",
	"Endless Love",
	"The Time Traveler's Wife",
	"P.S. I Love You"
];

// TV Shows
const tvshows = [
	"Breaking Bad",
	"Game of Thrones",
	"Friends",
	"The Office (US)",
	"Stranger Things",
	"The Simpsons",
	"The Mandalorian",
	"The Walking Dead",
	"Sherlock",
	"Better Call Saul",
	"The Crown",
	"True Detective",
	"The Big Bang Theory",
	"Parks and Recreation",
	"How I Met Your Mother",
	"Brooklyn Nine-Nine",
	"Fargo",
	"Westworld",
	"Black Mirror",
	"Narcos",
	"House of Cards",
	"The Witcher",
	"The Marvelous Mrs. Maisel",
	"Mad Men",
	"Dexter",
	"Lost",
	"Suits",
	"Grey’s Anatomy",
	"The Boys",
	"Supernatural",
	"The X-Files",
	"Rick and Morty",
	"Doctor Who",
	"Arrow",
	"Lucifer",
	"Vikings",
	"Peaky Blinders",
	"BoJack Horseman",
	"The Handmaid's Tale",
	"Big Little Lies",
	"The West Wing",
	"The Good Place",
	"Money Heist",
	"The Umbrella Academy",
	"The Sopranos",
	"Charmed",
	"Buffy the Vampire Slayer",
	"Supergirl",
	"Riverdale",
	"The Flash",
	"Arrow",
	"Jessica Jones",
	"Daredevil",
	"Luke Cage",
	"Iron Fist",
	"Gotham",
	"Smallville",
	"The 100",
	"The Expanse",
	"The OA",
	"Mindhunter",
	"Orange Is the New Black",
	"13 Reasons Why",
	"Sense8",
	"The Punisher",
	"Ozark",
	"The Good Doctor",
	"House M.D.",
	"Bones",
	"NCIS",
	"CSI: Crime Scene Investigation",
	"Law & Order: SVU",
	"Criminal Minds",
	"Blue Bloods",
	"The Blacklist",
	"Homeland",
	"Billions",
	"Chernobyl",
	"Twin Peaks",
	"The Wire",
	"Boardwalk Empire",
	"Succession",
	"The Leftovers",
	"The Newsroom",
	"The Morning Show",
	"Fleabag",
	"Euphoria",
	"Insecure",
	"Atlanta",
	"This Is Us",
	"Modern Family",
	"Schitt’s Creek",
	"Archer",
	"Veep",
	"Silicon Valley",
	"The IT Crowd",
	"Community",
	"30 Rock",
	"Scrubs",
	"Malcolm in the Middle",
	"The Middle",
	"Two and a Half Men",
	"Will & Grace",
	"Sex and the City",
	"Entourage",
	"The Wire",
	"True Blood",
	"Deadwood",
	"Band of Brothers",
	"The Pacific",
	"Generation Kill",
	"The Mandalorian",
	"WandaVision",
	"The Falcon and the Winter Soldier",
	"Loki",
	"Hawkeye",
	"Ms. Marvel",
	"Moon Knight",
	"She-Hulk",
	"The Book of Boba Fett",
	"Star Trek: The Next Generation",
	"Star Trek: Deep Space Nine",
	"Star Trek: Voyager",
	"Star Trek: Discovery",
	"Star Trek: Picard",
	"Battlestar Galactica",
	"Firefly",
	"Fringe",
	"Stargate SG-1",
	"Stargate Atlantis",
	"The Twilight Zone",
	"Futurama",
	"South Park",
	"Family Guy",
	"Bob's Burgers",
	"American Dad!",
	"The Cleveland Show",
	"Adventure Time",
	"Regular Show",
	"The Legend of Korra",
	"Avatar: The Last Airbender",
	"SpongeBob SquarePants",
	"Phineas and Ferb",
	"Gravity Falls",
	"The Amazing World of Gumball",
	"Steven Universe",
	"Star vs. the Forces of Evil",
	"Teen Titans Go!",
	"Young Justice",
	"Justice League",
	"Batman: The Animated Series",
	"Superman: The Animated Series",
	"Samurai Jack",
	"The Boondocks",
	"King of the Hill",
	"Beavis and Butt-Head",
	"Daria",
	"Robot Chicken",
	"Rick and Morty",
	"Solar Opposites",
	"Disenchantment",
	"BoJack Horseman",
	"Tuca & Bertie",
	"Big Mouth",
	"F Is for Family",
	"The Midnight Gospel",
	"Love, Death & Robots",
	"Castlevania",
	"Dragon Ball Z",
	"Naruto",
	"One Piece",
	"Attack on Titan",
	"My Hero Academia",
	"Demon Slayer",
	"Hunter x Hunter",
	"Sword Art Online",
	"Fullmetal Alchemist: Brotherhood",
	"Death Note",
	"Cowboy Bebop",
	"Neon Genesis Evangelion",
	"One Punch Man",
	"Bleach",
	"Fairy Tail",
	"Dragon Ball Super"
];

// Books
const books = [
	"To Kill a Mockingbird",
	"1984",
	"The Great Gatsby",
	"Pride and Prejudice",
	"Moby-Dick",
	"War and Peace",
	"Crime and Punishment",
	"The Catcher in the Rye",
	"Brave New World",
	"The Hobbit",
	"The Lord of the Rings",
	"The Odyssey",
	"Les Misérables",
	"Frankenstein",
	"The Picture of Dorian Gray",
	"Jane Eyre",
	"Wuthering Heights",
	"Anna Karenina",
	"Dracula",
	"Don Quixote",
	"Great Expectations",
	"A Tale of Two Cities",
	"The Brothers Karamazov",
	"The Grapes of Wrath",
	"Slaughterhouse-Five",
	"One Hundred Years of Solitude",
	"The Road",
	"Catch-22",
	"Lolita",
	"The Stranger",
	"The Alchemist",
	"The Kite Runner",
	"Fahrenheit 451",
	"The Scarlet Letter",
	"Of Mice and Men",
	"The Sun Also Rises",
	"The Handmaid’s Tale",
	"The Hunger Games",
	"The Book Thief",
	"Life of Pi",
	"Dune",
	"The Time Machine",
	"The War of the Worlds",
	"The Invisible Man",
	"Ender's Game",
	"Foundation",
	"Neuromancer",
	"The Expanse",
	"The Name of the Wind",
	"Mistborn",
	"The Way of Kings",
	"The Lies of Locke Lamora",
	"Harry Potter and the Sorcerer’s Stone",
	"Harry Potter and the Chamber of Secrets",
	"Harry Potter and the Prisoner of Azkaban",
	"Harry Potter and the Goblet of Fire",
	"Harry Potter and the Order of the Phoenix",
	"Harry Potter and the Half-Blood Prince",
	"Harry Potter and the Deathly Hallows",
	"Percy Jackson & the Olympians: The Lightning Thief",
	"The Sea of Monsters",
	"The Titan’s Curse",
	"The Battle of the Labyrinth",
	"The Last Olympian",
	"The Da Vinci Code",
	"Angels & Demons",
	"Digital Fortress",
	"The Lost Symbol",
	"Inferno",
	"The Girl with the Dragon Tattoo",
	"The Girl Who Played with Fire",
	"The Girl Who Kicked the Hornet’s Nest",
	"Gone Girl",
	"Sharp Objects",
	"Dark Places",
	"The Silence of the Lambs",
	"Red Dragon",
	"Hannibal",
	"The Stand",
	"It",
	"The Shining",
	"Carrie",
	"Pet Sematary",
	"The Outsider",
	"Under the Dome",
	"11/22/63",
	"American Gods",
	"Good Omens",
	"The Sandman",
	"Neverwhere",
	"Anansi Boys",
	"Coraline",
	"The Graveyard Book",
	"The Ocean at the End of the Lane",
	"The Fault in Our Stars",
	"Looking for Alaska",
	"Paper Towns",
	"Will Grayson, Will Grayson",
	"Eleanor & Park",
	"Fangirl",
	"Carry On",
	"Leviathan Wakes",
	"Caliban's War",
	"Abaddon’s Gate",
	"Cibola Burn",
	"Nemesis Games",
	"Babylon's Ashes",
	"Persepolis Rising",
	"Tiamat's Wrath",
	"Revelation Space",
	"Chasm City",
	"Redemption Ark",
	"Absolution Gap",
	"The Long Way to a Small, Angry Planet",
	"A Closed and Common Orbit",
	"Record of a Spaceborn Few",
	"Hyperion",
	"The Fall of Hyperion",
	"The Diamond Age",
	"Snow Crash",
	"The Three-Body Problem",
	"The Dark Forest",
	"Death's End",
	"The Left Hand of Darkness",
	"Kindred",
	"Parable of the Sower",
	"Dawn",
	"Oryx and Crake",
	"The Blind Assassin",
	"Station Eleven",
	"The Road",
	"The Martian",
	"Artemis",
	"Red Rising",
	"Golden Son",
	"Morning Star",
	"Iron Gold",
	"Dark Age",
	"Cinder",
	"Scarlet",
	"Cress",
	"Winter",
	"The Maze Runner",
	"The Scorch Trials",
	"The Death Cure",
	"The Kill Order",
	"The Fever Code",
	"Divergent",
	"Insurgent",
	"Allegiant",
	"The Giver",
	"Gathering Blue",
	"Messenger",
	"Son",
	"The Perks of Being a Wallflower",
	"Thirteen Reasons Why",
	"The Curious Incident of the Dog in the Night-Time",
	"The Lovely Bones",
	"The Help",
	"Water for Elephants",
	"Memoirs of a Geisha",
	"The Night Circus",
	"The Shadow of the Wind",
	"The Book Thief",
	"Cloud Atlas",
	"The Night Manager",
	"Tinker Tailor Soldier Spy",
	"The Spy Who Came in from the Cold",
	"The Bourne Identity",
	"The Hunt for Red October",
	"Patriot Games",
	"Clear and Present Danger",
	"The Sum of All Fears",
	"Red Storm Rising",
	"Without Remorse",
	"The Secret Garden",
	"Little Women",
	"Anne of Green Gables",
	"The Chronicles of Narnia",
	"Charlotte's Web",
	"The Wind in the Willows",
	"Peter Pan",
	"Alice's Adventures in Wonderland",
	"The Wonderful Wizard of Oz",
	"Winnie-the-Pooh",
	"The Little Prince",
	"Charlie and the Chocolate Factory",
	"Matilda",
	"James and the Giant Peach",
	"The BFG",
	"The Twits",
	"The Witches",
	"The Phantom Tollbooth",
	"Where the Wild Things Are",
	"Holes",
	"The Giver",
	"The Outsiders",
	"Bridge to Terabithia",
	"The Westing Game",
	"The Mysterious Benedict Society",
	"A Wrinkle in Time",
	"Ender's Game",
	"The Golden Compass"
];

// Sayings and Phrases
const sayings = [
	"A bird in the hand is worth two in the bush",
	"A blessing in disguise",
	"A diamond in the rough",
	"A drop in the bucket",
	"A fool and his money are soon parted",
	"A leopard can't change its spots",
	"A penny saved is a penny earned",
	"A picture is worth a thousand words",
	"A piece of cake",
	"A stitch in time saves nine",
	"Actions speak louder than words",
	"All that glitters is not gold",
	"An apple a day keeps the doctor away",
	"An eye for an eye makes the whole world blind",
	"Barking up the wrong tree",
	"Beating around the bush",
	"Better late than never",
	"Birds of a feather flock together",
	"Break the ice",
	"Burn the midnight oil",
	"Burning the candle at both ends",
	"Bite the bullet",
	"Bite off more than you can chew",
	"By the skin of your teeth",
	"Cat's got your tongue?",
	"Caught between a rock and a hard place",
	"Close but no cigar",
	"Cold feet",
	"Cry over spilled milk",
	"Curiosity killed the cat",
	"Cut corners",
	"Devil's advocate",
	"Don't count your chickens before they hatch",
	"Don't judge a book by its cover",
	"Don't put all your eggs in one basket",
	"Easier said than done",
	"Every cloud has a silver lining",
	"Fall on deaf ears",
	"Feel like a fish out of water",
	"Fit as a fiddle",
	"Get cold feet",
	"Give someone the cold shoulder",
	"Go the extra mile",
	"Good things come to those who wait",
	"Haste makes waste",
	"Have a chip on your shoulder",
	"Hit the nail on the head",
	"Ignorance is bliss",
	"In a nutshell",
	"It takes two to tango",
	"Jump the gun",
	"Keep your chin up",
	"Kill two birds with one stone",
	"Let the cat out of the bag",
	"Like father, like son",
	"Like two peas in a pod",
	"Live and learn",
	"Look before you leap",
	"Make hay while the sun shines",
	"Miss the boat",
	"Money doesn't grow on trees",
	"Needle in a haystack",
	"No pain, no gain",
	"Off the top of your head",
	"On thin ice",
	"Out of the frying pan into the fire",
	"Out of sight, out of mind",
	"Over the moon",
	"Piece of cake",
	"Practice makes perfect",
	"Pull the wool over someone's eyes",
	"Put your best foot forward",
	"Raining cats and dogs",
	"Rome wasn't built in a day",
	"Shoot for the moon",
	"Skeleton in the closet",
	"Spill the beans",
	"The ball is in your court",
	"The early bird catches the worm",
	"The pen is mightier than the sword",
	"The pot calling the kettle black",
	"There's no such thing as a free lunch",
	"Throw caution to the wind",
	"Throw in the towel",
	"Time flies when you're having fun",
	"Too many cooks spoil the broth",
	"Turn a blind eye",
	"Under the weather",
	"You can lead a horse to water, but you can't make him drink",
	"You can't judge a book by its cover",
	"Your guess is as good as mine",
	"You reap what you sow",
	"Beggars can't be choosers",
	"Better safe than sorry",
	"Don't bite the hand that feeds you",
	"Fortune favors the bold",
	"In for a penny, in for a pound",
	"It’s always darkest before the dawn",
	"Keep your friends close and your enemies closer",
	"Kill two birds with one stone",
	"Laugh and the world laughs with you, weep and you weep alone",
	"Let sleeping dogs lie",
	"Life is short, art is long",
	"Live and let live",
	"Look before you leap",
	"Make a mountain out of a molehill",
	"Necessity is the mother of invention",
	"No use crying over spilled milk",
	"Old habits die hard",
	"Once bitten, twice shy",
	"Out of the blue",
	"Penny for your thoughts",
	"Practice what you preach",
	"Put the cart before the horse",
	"Rags to riches",
	"Revenge is a dish best served cold",
	"Rome wasn't built in a day",
	"Slow and steady wins the race",
	"Speak of the devil",
	"Still waters run deep",
	"Strike while the iron is hot",
	"The best of both worlds",
	"The devil is in the details",
	"The early bird catches the worm",
	"The grass is always greener on the other side",
	"The squeaky wheel gets the grease",
	"There are plenty more fish in the sea",
	"There's no place like home",
	"Throw in the towel",
	"Time heals all wounds",
	"To add insult to injury",
	"To each his own",
	"Turn over a new leaf",
	"Two wrongs don’t make a right",
	"Waste not, want not",
	"When in Rome, do as the Romans do",
	"When the going gets tough, the tough get going",
	"Where there's smoke, there's fire",
	"You can't have your cake and eat it too",
	"You can't make an omelette without breaking eggs",
	"You win some, you lose some",
	"Your bark is worse than your bite",
	"You can't teach an old dog new tricks",
	"Actions speak louder than words",
	"All’s well that ends well",
	"Blood is thicker than water",
	"Don’t bite off more than you can chew",
	"Don’t count your chickens before they hatch",
	"Every dog has its day",
	"Familiarity breeds contempt",
	"Good fences make good neighbors",
	"Hope for the best, prepare for the worst",
	"If it ain't broke, don't fix it",
	"If the shoe fits, wear it",
	"In the heat of the moment",
	"It's a small world",
	"It takes two to tango",
	"Jump on the bandwagon",
	"Let bygones be bygones",
	"No guts, no glory",
	"One man’s trash is another man’s treasure",
	"Play your cards right",
	"Put your money where your mouth is",
	"The apple doesn’t fall far from the tree",
	"The bigger they are, the harder they fall",
	"The best things in life are free",
	"The grass is always greener on the other side",
	"There’s no time like the present",
	"Two heads are better than one",
	"What goes around comes around",
	"Where there’s a will, there’s a way",
	"You can’t judge a book by its cover",
	"You can’t have it both ways",
	"You live and learn"
];

// Plays
const plays = [
	"Hamlet",
	"Romeo and Juliet",
	"Macbeth",
	"Othello",
	"King Lear",
	"The Tempest",
	"A Midsummer Night's Dream",
	"Twelfth Night",
	"Julius Caesar",
	"Antony and Cleopatra",
	"The Merchant of Venice",
	"As You Like It",
	"Much Ado About Nothing",
	"The Taming of the Shrew",
	"The Comedy of Errors",
	"Measure for Measure",
	"The Winter's Tale",
	"Richard III",
	"Henry V",
	"Henry IV, Part 1",
	"Henry IV, Part 2",
	"Richard II",
	"Coriolanus",
	"Titus Andronicus",
	"Troilus and Cressida",
	"All's Well That Ends Well",
	"Love's Labour's Lost",
	"The Merry Wives of Windsor",
	"Pericles",
	"Cymbeline",
	"King John",
	"The Two Gentlemen of Verona",
	"The Two Noble Kinsmen",
	"The Crucible",
	"Death of a Salesman",
	"A Streetcar Named Desire",
	"Long Day's Journey Into Night",
	"Cat on a Hot Tin Roof",
	"The Glass Menagerie",
	"Who's Afraid of Virginia Woolf?",
	"A Raisin in the Sun",
	"The Importance of Being Earnest",
	"Waiting for Godot",
	"No Exit",
	"Pygmalion",
	"Arms and the Man",
	"The Cherry Orchard",
	"Uncle Vanya",
	"The Seagull",
	"Three Sisters",
	"The Iceman Cometh",
	"The Hairy Ape",
	"Fences",
	"The Piano Lesson",
	"Topdog/Underdog",
	"August: Osage County",
	"Inherit the Wind",
	"The Night of the Iguana",
	"The Little Foxes",
	"Our Town",
	"The Children's Hour",
	"The Zoo Story",
	"Equus",
	"Amadeus",
	"The Elephant Man",
	"Les Misérables",
	"Miss Saigon",
	"Sweeney Todd",
	"Phantom of the Opera",
	"Wicked",
	"The Book of Mormon",
	"Hamilton",
	"Rent",
	"Chicago",
	"The Lion King",
	"West Side Story",
	"Fiddler on the Roof",
	"Hairspray",
	"Cabaret",
	"A Chorus Line",
	"My Fair Lady",
	"Evita",
	"Jesus Christ Superstar",
	"South Pacific",
	"Oklahoma!",
	"Carousel",
	"The King and I",
	"The Sound of Music",
	"Into the Woods",
	"Sunday in the Park with George",
	"Company",
	"A Funny Thing Happened on the Way to the Forum",
	"Guys and Dolls",
	"Kiss Me, Kate",
	"Anything Goes",
	"Gypsy",
	"Mamma Mia!",
	"Les Liaisons Dangereuses",
	"The Phantom of the Opera",
	"The Homecoming",
	"Betrayal",
	"Look Back in Anger",
	"The Caretaker",
	"The Birthday Party",
	"Rosencrantz and Guildenstern Are Dead",
	"Arcadia",
	"The Real Thing",
	"The Coast of Utopia",
	"The History Boys",
	"Art",
	"The Pillowman",
	"Jerusalem",
	"Blackbird",
	"Venus in Fur",
	"Red",
	"Doubt",
	"The Normal Heart",
	"Angels in America",
	"The Inheritance",
	"The Ferryman",
	"Harry Potter and the Cursed Child",
	"Peter and the Starcatcher",
	"Matilda the Musical",
	"Billy Elliot",
	"War Horse",
	"Curious Incident of the Dog in the Night-Time",
	"An Inspector Calls",
	"Travesties",
	"The School for Scandal",
	"She Stoops to Conquer",
	"The Rivals",
	"Doctor Faustus",
	"Tamburlaine",
	"The Alchemist",
	"Volpone",
	"Edward II",
	"The Duchess of Malfi",
	"The Changeling",
	"The Jew of Malta",
	"The Spanish Tragedy",
	"Everyman",
	"The Bacchae",
	"Oedipus Rex",
	"Antigone",
	"Lysistrata",
	"The Birds",
	"Medea",
	"Hippolytus",
	"Prometheus Bound",
	"The Oresteia",
	"Electra",
	"Ajax",
	"The Frogs",
	"Iphigenia in Aulis",
	"Iphigenia in Tauris",
	"The Persians",
	"Philoctetes",
	"Alcestis",
	"Helen",
	"Women of Troy",
	"The Clouds",
	"Phaedra",
	"Andromache",
	"Trojan Women",
	"The Wasps",
	"The Knights",
	"The Assemblywomen",
	"Seven Against Thebes",
	"Suppliants",
	"The Eumenides",
	"Agamemnon",
	"Choephori",
	"The Phoenician Women",
	"The Golden Ass",
	"Cupid and Psyche",
	"Metamorphoses",
	"The Miser",
	"Tartuffe",
	"The Misanthrope",
	"Don Juan",
	"Phaedra",
	"The Hypochondriac",
	"The Doctor in Spite of Himself",
	"The Imaginary Invalid",
	"The School for Wives",
	"The Rehearsal",
	"The Barber of Seville",
	"The Marriage of Figaro",
	"Cyrano de Bergerac",
	"The Master Builder",
	"Peer Gynt",
	"A Doll's House",
	"Ghosts",
	"Hedda Gabler",
	"Miss Julie",
	"A Dream Play"
];

function showRandomItem(category) {
	const randomIndex = Math.floor(Math.random() * category.length);
	const randomItem = category[randomIndex];
	const randomItemContainer = document.getElementById('random-item');
	randomItemContainer.innerHTML = randomItem;
}

function getRandomEmoticons() {
	const emoticons = [
		'😀', '😂', '😍', '😎', '😊', '🤔', '😜', '🙃', '😢', '😡', '😱', '🤯', '🤖',
		'👻', '👽', '💀', '🎃', '😺', '💩', '🎉', '💥', '🌈', '☀️', '🌙', '⭐️', '🔥',
		'⚡️', '🍕', '🍔', '🍟', '🍣', '🍜', '🍦', '🍩', '🍪', '🎈', '🎵', '🎮', '🏀',
		'⚽', '🚗', '✈️', '🚀', '💎', '🔑', '🔨', '💡', '📱', '💻'
	];

	let randomEmoticons = '';

	for (let i = 0; i < 8; i++) {
		const randomIndex = Math.floor(Math.random() * emoticons.length);
		randomEmoticons += emoticons[randomIndex];
	}

	return randomEmoticons;
}